---
name: CI
on:
  pull_request:
    types: [opened, reopened]

jobs:
  lint:
    name: Lint markdown files
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Lint markdown files
      uses: docker://avtodev/markdown-lint:v1
      with:
        args: '.'
